# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Suporte Work Sistemas
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Solução em Ponto Eletrônico
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://suporte.biofinger.com.br" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
#twitter_username: 
#github_username:  
#facebook_username: 
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: Rua Independência, 880, Sala 02
address_city: Marechal Cândido Rondon
address_state: PR
address_zip: 85960-000

# Build settings
markdown: kramdown
